// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erancrjvrtmwstpuysgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyYW5jcmp2cnRtd3N0cHV5c2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDUyOTMsImV4cCI6MjA2NzU4MTI5M30.THkbADoYPm6745AMu1r46wC5qC4ZdcZFL_ZqLJTFBVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});